'use strict';
const assert=require('node:assert/strict');
const core=require('../app-core.js'),seat=require('../seating-data.js');
const pupil=(name,cls,total,physics,math)=>({name,class:cls,subjects:{总分:{score:total,gradeRank:1000},物理:{score:physics},数学:{score:math}}});
const data=[pupil('甲','801',100,100,0),pupil('乙','01班',80,0,100),pupil('丙','一班',60,50,50),pupil('丁','701',40,'缺考',25),pupil('甲','802',999,999,999)];
const profiles=seat.buildProfiles(data,[],'01班','总分',[],[]);
assert.equal(profiles.length,4);assert.equal(profiles[0].totalPopulation,4);assert.equal(profiles[0].totalPercentile,25);
assert.equal(profiles.find(p=>p.name==='丁').totalPercentile,100);
assert.equal(profiles.find(p=>p.name==='乙').subjects.物理.score,0);
assert.equal(profiles.find(p=>p.name==='丁').subjects.物理.rank,null);
assert.ok(!profiles.find(p=>p.name==='丁').weaks.includes('物理'));
const state=seat.reconcile(profiles,null),a=state.students.find(s=>s.name==='甲'),b=state.students.find(s=>s.name==='乙'),d=state.students.find(s=>s.name==='丁');
assert.deepEqual(seat.complementDetails(a,b).map(x=>x.subject),['数学','物理']);
assert.deepEqual(seat.complementDetails(a,d).map(x=>x.subject),['数学'],'missing scores must not imply weakness');
assert.equal(a.compositeRank,25);assert.equal(d.compositeRank,100);
assert.deepEqual(seat.complementDetails({name:'x',subjects:{物理:{rank:null,percentile:null}}},b),[]);
const ties=seat.buildProfiles(Array.from({length:8},(_,i)=>pupil('同分'+i,'01班',50,50,50)),[],'01班','总分',[],[]);
assert.ok(ties.every(p=>p.totalRank===1 && p.totalPercentile===12.5 && !p.weaks.length),'ties must not be split into stronger/weaker pupils');
const singleton=seat.buildProfiles([pupil('唯一','01班',50,50,50)],[],'01班','总分',[],[]);
assert.equal(singleton[0].totalPercentile,null);
const empty=seat.buildProfiles([{name:'缺考',class:'01班',subjects:{总分:{score:''}}},{name:'未知',class:'01班',subjects:{总分:{score:'缺考'}}}],[],'01班','总分',[],[]);
assert.ok(empty.every(p=>p.totalPercentile===null && !p.leads.length && !p.weaks.length));
const noTotal=data.map(s=>({...s,subjects:{物理:s.subjects.物理,数学:s.subjects.数学}}));
const composite=seat.buildProfiles(noTotal,[],'01班','',[],[]);
assert.equal(composite.find(p=>p.name==='丁').totalRank,null,'incomplete subjects must not create a favorable composite');
const scoreAndRank=seat.subjectMetrics([{name:'有分',class:'01班',subjects:{物理:{score:0,gradeRank:999}}},{name:'没分',class:'01班',subjects:{物理:{score:'',gradeRank:1}}}],'物理');
assert.equal(scoreAndRank.size,1,'do not mix score and original ranking populations');
const rankOnly=seat.subjectMetrics([{name:'排名甲',class:'01班',subjects:{物理:{score:'',gradeRank:500}}},{name:'排名乙',class:'01班',subjects:{物理:{gradeRank:900}}},{name:'缺考',class:'01班',subjects:{物理:{score:'缺考',gradeRank:1}}}],'物理');
assert.equal(rankOnly.size,2);assert.equal(rankOnly.get(core.studentKey({name:'排名甲',class:'01班'})).percentile,50);
assert.equal(rankOnly.get(core.studentKey({name:'排名乙',class:'01班'})).percentile,100);
const history=[{combinedStudentData:data,allSubjectHeaders:[{name:'总分'}]}];
assert.deepEqual(seat.buildProfiles(data,[],'02班','总分',history,[])[0].totalTrendRanks,[1],'class-aware trend identity must disambiguate duplicate names');
state.students[0].status='fixed';state.students[0].tags=['自律'];state.seatMap[4]='🚫';
const changed=data.map(s=>s.name==='丙'?pupil('丙',s.class,120,60,50):s);
const refreshed=seat.reconcile(seat.buildProfiles(changed,[],'01班','总分',[],[]),state);
assert.deepEqual(refreshed.seatMap,state.seatMap);assert.equal(refreshed.students.find(s=>s.name===state.students[0].name).status,'fixed');
assert.deepEqual(refreshed.students.find(s=>s.name===state.students[0].name).tags,['自律']);
assert.equal(refreshed.students.find(s=>s.name==='丙').latestTotalRank,1);
const rosterSaved=core.clone(state);rosterSaved.seatMap[rosterSaved.seatMap.indexOf('乙')]=null;
const newRoster=data.filter(s=>s.name!=='丙').concat(pupil('新生','01班',75,60,50));
const joined=seat.reconcile(seat.buildProfiles(newRoster,[],'01班','总分',[],[]),rosterSaved);
assert.ok(joined.seatMap.includes('新生'));assert.ok(!joined.seatMap.includes('丙'));assert.ok(!joined.seatMap.includes('乙'));
assert.equal(joined.seatMap[4],'🚫');assert.equal(joined.seatMap.indexOf('甲'),state.seatMap.indexOf('甲'));
const original=['甲','乙','丙','丁',null,null,null,null],duplicate=['甲','乙','甲','乙','甲','乙',null,null];
const fixed=state.students.map(s=>({...s,status:s.name==='甲'?'fixed':'normal'}));
const repaired=seat.repairMap(duplicate,fixed,original);assert.ok(seat.validMap(repaired,fixed,original));
assert.equal(repaired.filter(Boolean).length,4);assert.equal(new Set(repaired.filter(Boolean)).size,4);assert.equal(repaired[0],'甲');
const blocked=original.slice();blocked[7]='🚫';assert.equal(seat.repairMap(duplicate,fixed,blocked)[7],'🚫');
const groups=seat.groups(Array(24).fill(null),6);assert.ok(groups.every(g=>g.length===6));assert.equal(new Set(groups.flat()).size,24);
(async()=>{
 const memory=new Map(),journal=new Map();let fail=false;
 const storage={read:async k=>core.clone(memory.get(k)),write:async(k,v)=>{if(fail)throw new Error('quota');memory.set(k,core.clone(v))}};
 const local={getItem:k=>journal.get(k) || null,setItem:(k,v)=>journal.set(k,v)};
 const store=seat.createStore(storage,local),entries=[];
 for(let i=0;i<15;i++){const snap={id:'snap'+i,className:'01班',students:state.students,seatMap:state.seatMap,reason:'调整'};entries.push({id:snap.id});await store.save('01班',snap,entries).promise;}
 const recovered=await store.load('01班');assert.equal(recovered.history.length,15,'do not truncate history to ten snapshots');
 assert.ok((await store.snapshot('01班',entries[0])).students.length);
 fail=true;const pending={id:'pending',className:'01班',students:state.students,seatMap:state.seatMap.slice()};entries.push({id:'pending'});
 const saved=store.save('01班',pending,entries);assert.equal(saved.localSaved,true);await assert.rejects(saved.promise);
 const reopened=seat.createStore(storage,local);assert.equal((await reopened.load('01班')).latest.id,'pending','synchronous journal survives an interrupted database write');
 assert.equal((await reopened.snapshot('01班',{id:'pending'})).id,'pending');
 fail=false;await reopened.save('01班',pending,entries).promise;assert.equal((await store.load('01班')).history.length,16);
 await store.save('02班',{id:'other',students:[],seatMap:[]},[{id:'other'}]).promise;
 assert.equal((await store.load('01班')).latest.id,'pending');assert.equal((await store.load('02班')).latest.id,'other');
 assert.deepEqual((await store.classes()).sort(),['01班','02班']);
 const projectA=seat.createStore(storage,local,'/a/'),projectB=seat.createStore(storage,local,'/b/');
 await projectA.save('01班',{id:'projectA',students:[],seatMap:[]},[{id:'projectA'}]).promise;
 assert.equal(await projectB.load('01班'),null);assert.deepEqual(await projectB.classes(),[]);
 assert.equal((await projectA.load('01班')).latest.id,'projectA');
 console.log('PASS seating: current-class metrics, ties, zero/missing scores, complement consistency, history identity, reconciliation, fixed/blocked seats, append-only records and interrupted-write recovery');
})().catch(e=>{console.error(e);process.exitCode=1});
