'use strict';
const assert=require('node:assert/strict'),data=require('../seating-data.js'),engine=require('../seating-engine.js');
const headers=[{name:'总分'},{name:'数学'},{name:'物理'}];
const row=(name,total,math,physics,cls='01班')=>({name,class:cls,subjects:{总分:total,数学:math,物理:physics}});
const first=[row('甲',{gradeRank:10,score:80},{gradeRank:20,score:0},{gradeRank:80,score:20}),row('乙',{gradeRank:25,score:70},{gradeRank:70,score:10},{gradeRank:20,score:80})];
const second=[row('甲',{gradeRank:40},{gradeRank:20},{gradeRank:1,score:'缺考'}),row('乙',{gradeRank:60},{gradeRank:180},{gradeRank:40})];
const batches=[{id:'A',label:'考试A',combinedStudentData:first,allSubjectHeaders:headers},{id:'B',label:'考试B',combinedStudentData:second,allSubjectHeaders:headers},{id:'C',label:'无关考试',combinedStudentData:[],allSubjectHeaders:headers}];
const options={currentExam:'A',compareExam:'B',scope:'grade',populations:{A:{'*':100},B:{'*':200,物理:100}}};
const profiles=data.buildProfiles(first,headers,'01班','总分',batches,[],options),a=profiles.find(s=>s.name==='甲'),b=profiles.find(s=>s.name==='乙');
assert.equal(a.totalPercentile,15);assert.equal(b.totalPercentile,27.5);assert.equal(a.sampleCount,2);
assert.equal(a.subjects.数学.percentile,15);assert.equal(a.subjects.数学.score,0);assert.equal(a.subjects.物理.percentile,80);assert.equal(a.subjects.物理.sampleCount,1);
assert.equal(b.subjects.物理.percentile,30);assert.equal(a.tier,'L2');assert.equal(b.tier,'L3');
assert.deepEqual(a.examLabels,['考试A','考试B']);assert.equal(a.academicScope,'grade');
assert.deepEqual(data.complementDetails(a,b).map(h=>h.helper),['甲','乙']);
assert.equal(data.buildProfiles(first,headers,'01班','总分',batches,[],{...options,compareExam:''})[0].sampleCount,1,'unselected history must not be averaged');
assert.equal(data.examSources(first,headers,'总分',batches,{currentExam:'@current',compareExam:'A',currentBatchId:'A'}).length,1,'the same exam must not be counted twice');
assert.equal(data.examSources(first,headers,'总分',batches,{currentExam:'deleted'}).length,0);
const insufficient=data.buildProfiles(first,headers,'01班','总分',batches,[],{scope:'grade'});
assert.ok(insufficient.every(s=>s.totalPercentile===null),'a partial class ranking needs a grade denominator');
assert.equal(data.buildProfiles(first,headers,'01班','总分',batches,[],{currentExam:'A',compareExam:'B',scope:'auto',populations:{A:{'*':100}}})[0].academicScope,'class','auto fallback applies consistently to both selected exams');
const rankText=[row('甲',{gradeRank:'10/100'},{gradeRank:'20/100'},{gradeRank:'80/100'}),row('乙',{gradeRank:'25/100'},{gradeRank:'70/100'},{gradeRank:'20/100'})];
assert.equal(data.buildProfiles(rankText,headers,'01班','总分',[],[],{scope:'auto'})[0].totalPercentile,10);
assert.equal(data.examMetrics({...batches[0],combinedStudentData:rankText},'总分','01班','grade',{populations:{A:{'*':5}}}).size,0,'invalid denominators cannot create a favorable rank');
const full=[row('甲',{score:100},{score:0},{score:50}),row('乙',{score:90},{score:50},{score:'缺考'}),row('丙',{score:90},{score:100},{score:60},'02班'),row('丁',{score:70},{score:75},{score:80},'02班')];
assert.equal(data.buildProfiles(full,headers,'01班','总分',[],[],{} )[0].academicScope,'class','several classes alone do not prove full-grade coverage');
const grade=data.buildProfiles(full,headers,'01班','总分',[],[],{completeGrades:{'@current':true}});
assert.equal(grade[0].totalPercentile,25);assert.equal(grade[1].totalPercentile,50);assert.equal(grade[0].totalPopulation,4);assert.equal(grade[0].subjects.物理.population,3);
assert.equal(data.examMetrics({id:'@current',combinedStudentData:full},'总分','01班','grade',{completeGrades:{'@current':true},populations:{'@current':{'*':100}}}).size,0,'scores in a partial grade cannot be expanded by inventing a population');
for(const [p,t] of [[12.5,1],[12.5001,2],[25,2],[25.0001,3],[100,8],[null,0]])assert.equal(data.layer(p),t);
assert.equal(data.complementDetails({name:'a',subjects:{x:{percentile:12.5}}},{name:'b',subjects:{x:{percentile:22.5}}}).length,1);
assert.equal(data.complementDetails({name:'a',subjects:{x:{percentile:12.5}}},{name:'b',subjects:{x:{percentile:22.49}}}).length,0);
assert.equal(data.complementDetails({name:'a',subjects:{x:{percentile:1}}},{name:'b',subjects:{x:{percentile:100}}})[0].urgency,3);
const pupil=(i,p)=>({name:'S'+i,compositeRank:p,status:'normal',tags:[],subjects:{数学:{percentile:[5,20,35,50,65,80,95,40][i]},物理:{percentile:[95,80,65,50,35,20,5,60][i]}}});
const students=Array.from({length:8},(_,i)=>pupil(i,10+i*5)),map=students.map(s=>s.name),context=engine.prepare(students,map,{groupSize:4});
assert.equal(context.pairs.length,28);assert.equal(context.pairs.find(p=>p.i===0&&p.j===2).moderate,false);assert.equal(context.pairs.find(p=>p.i===0&&p.j===5).moderate,true);
assert.equal(context.pairs.find(p=>p.i===0&&p.j===6).allowed,false);
const metrics={dual:1,oneWay:1,crowding:1,mixed:1,own:1,horizontalStrength:1,verticalStrength:1,adjacent:0,moderate:1,balance:1,urgency:1,single:0,behavior:0};
for(const key of Object.keys(metrics)){
 const better={...metrics,[key]:metrics[key]+(key==='crowding'?-1:1)},worse={...metrics};let after=false;
 for(const next of Object.keys(metrics)){if(after)worse[next]=next==='crowding'?0:1000000;if(next===key)after=true;}
 assert.equal(engine.compare(better,worse,'academic'),1,'a later reward must not outweigh '+key);
}
let optimal=null,permutations=0;
function enumerate(prefix,remaining){if(!remaining.length){permutations++;if(engine.valid(context,prefix)){const m=engine.evaluate(context,prefix);if(engine.compare(m,optimal,'academic')>0)optimal=m;}return;}for(const i of remaining)enumerate(prefix.concat(i),remaining.filter(j=>j!==i));}
enumerate([],students.map((_,i)=>i));assert.equal(permutations,40320);
const result=engine.search(context,{seed:19,budgetMs:1500,maxEvaluations:50000});assert.equal(result.valid,true);assert.equal(engine.compare(result.metrics,optimal,'academic'),0,'small exhaustive reference validates the full priority order');
const plateau=students.map(s=>({...s,compositeRank:25,subjects:{x:{percentile:25}}})),run=engine.search(engine.prepare(plateau,map,{groupSize:4}),{seed:7,budgetMs:1500,maxEvaluations:2000});
assert.equal(run.evaluations,2000,'no improvement must not trigger a fifteen-round early stop');
const locked=students.map(s=>({...s,compositeRank:25}));locked[0].status='fixed';locked[6].compositeRank=null;
const sparse=['S0','S1','S2','S3','S4','S5','S6','🚫',null,null,null,null,null,null,null,null];
const safe=engine.search(engine.prepare(locked,sparse,{groupSize:6}),{seed:14,budgetMs:1500,maxEvaluations:2000});
assert.equal(safe.valid,true);assert.equal(safe.solution[0],'S0');assert.equal(safe.solution[7],'🚫');assert.deepEqual(safe.solution.slice(8),Array(8).fill(null));assert.ok(!safe.solution.includes('S7'),'waiting students must stay waiting');assert.equal(safe.solution[6],'S6','missing total may remain only at a single seat');
const bad=students.map(s=>({...s,status:'fixed'}));bad[0].tags=['关系不和:S1'];
const conflict=engine.prepare(bad,map,{groupSize:4});assert.equal(engine.valid(conflict,conflict.original),false);assert.equal(engine.evaluate(conflict,conflict.original).violations,1);
const noSolution=engine.search(conflict,{budgetMs:20});assert.equal(noSolution.valid,false);assert.equal(noSolution.solution,null);
assert.equal(engine.valid(context,Array(8).fill(NaN)),false);assert.throws(()=>engine.rebase(context,students,['unknown']),/未知/);
assert.equal(engine.rebase(context,students,map.slice().reverse()).allowed,context.allowed,'placement-only changes reuse the cached pairs');
const coverageStudents=Array.from({length:12},(_,i)=>({...pupil(i%8,10+i),name:'G'+i}));
const coverageMap=['G0','G1','G3','G4','G5','G6','G2','G7','G8','G9','G10','G11',null,null,null,null];
const coverage=engine.prepare(coverageStudents,coverageMap,{groupSize:4}),covered=engine.evaluate(coverage,coverage.original);
assert.equal(covered.own,2,'two anchors in one group only cover it once');assert.equal(covered.adjacent,2,'neighbor help only supplements uncovered occupied groups');
const spread=coverage.original.slice();[spread[1],spread[2]]=[spread[2],spread[1]];
assert.equal(engine.evaluate(coverage,spread).own,3);assert.equal(engine.evaluate(coverage,spread).adjacent,1);
const cutoff=engine.prepare(students.map((s,i)=>({...s,compositeRank:i<3?10:30+i})),map,{groupSize:4});assert.equal(cutoff.anchors.reduce((a,b)=>a+b),3,'cutoff ties are included in the top 20%');
const fifty=Array.from({length:50},(_,i)=>({...pupil(i%8,25),name:'N'+i}));assert.equal(engine.prepare(fifty,fifty.map(s=>s.name),{}).pairs.length,1225);
console.log('PASS seating academic: selected exams, independent grade denominators, missing/zero values, eight tiers, cached hard rules, 40,320 exhaustive arrangements, strict priorities and no stagnation cutoff');
