'use strict';
const assert=require('node:assert/strict'),D=require('../seating-data'),E=require('../seating-engine');
const rows=Array.from({length:9},(_,i)=>({name:'学生'+i,class:'01班',subjects:{总分:{score:100-i},数学:{score:i*10},物理:{score:100-i*10}}}));
const profiles=D.buildProfiles(rows,[],'01班','总分',[],[],{}),state=D.reconcile(profiles,null);
state.students.forEach(s=>s.compositeRank=25);state.students[0].status='fixed';
state.seatMap=state.students.slice(0,8).map(s=>s.name);state.seatIds=D.layoutIds(state.seatMap);
const waiting=state.students[8].name,fixedName=state.students[0].name,fixedId=state.seatIds[0];
let added=D.addSeats(state.seatMap,state.seatIds,{side:'top',col:0});
assert.equal(added.seatMap.length,16);assert.equal(added.seatIds.filter(Boolean).length,9,'one click adds one physical seat, not eight');assert.deepEqual(added.seatMap.slice(8),state.seatMap);assert.equal(added.seatIds[8],fixedId);assert.equal(added.seatIds[1],null);
const firstId=added.seatIds[0];added=D.addSeats(added.seatMap,added.seatIds,{index:1});assert.equal(added.seatIds[0],firstId);assert.equal(added.seatIds.filter(Boolean).length,10);
added=D.addSeats(added.seatMap,added.seatIds,{side:'bottom',whole:true});assert.equal(added.seatIds.filter(Boolean).length,18);assert.equal(new Set(added.seatIds.filter(Boolean)).size,18);
assert.throws(()=>D.addSeats(added.seatMap,added.seatIds,{index:0}),/已存在/);assert.throws(()=>D.addSeats(added.seatMap,added.seatIds,{side:'left',col:0}),/无效/);
const invalid=added.seatMap.slice();invalid[2]=waiting;assert.equal(D.validMap(invalid,state.students,invalid,added.seatIds),false);assert.throws(()=>E.prepare(state.students,invalid,{seatIds:added.seatIds}),/布局/);
const ids=added.seatIds.slice();ids[1]=ids[0];assert.equal(D.validSeatLayout(added.seatMap,ids),false);
const restored=D.reconcile(profiles,{...state,...added});assert.deepEqual(restored.seatMap,added.seatMap);assert.deepEqual(restored.seatIds,added.seatIds);assert.ok(!restored.seatMap.includes(waiting),'layout recovery must not pull waiting students back into seats');
assert.equal(restored.seatIds[restored.seatMap.indexOf(fixedName)],fixedId);
const filled=D.fillUnseated(state.students,added.seatMap,added.seatIds);assert.equal(filled.placed,1);assert.ok(filled.seatMap.includes(waiting));assert.deepEqual(filled.seatIds,added.seatIds);assert.equal(filled.seatMap[8],fixedName);assert.equal(added.seatMap.includes(waiting),false);
filled.seatIds.forEach((id,i)=>{if(id===null)assert.equal(filled.seatMap[i],null);});
const tight=state.seatMap.slice();tight[7]='🚫';const expanded=D.fillUnseated(state.students,tight,state.seatIds);assert.equal(expanded.placed,2);assert.equal(expanded.seatMap.length,16);assert.deepEqual(expanded.seatMap.slice(0,8),tight);assert.deepEqual(expanded.seatIds.slice(0,8),state.seatIds);assert.equal(expanded.seatMap.filter(n=>n && n!=='🚫').length,9);assert.equal(D.fillUnseated(state.students,expanded.seatMap,expanded.seatIds).placed,0);
const newRoster=rows.concat({name:'新生',class:'01班',subjects:{总分:{score:90}}}),joined=D.reconcile(D.buildProfiles(newRoster,[],'01班','总分',[],[],{}),{...state,...added});
assert.ok(joined.seatMap.includes('新生'));assert.ok(joined.seatIds[joined.seatMap.indexOf('新生')]);assert.ok(!joined.seatMap.includes(waiting));
const map=added.seatMap.slice(),name=map[9];map[9]=null;map[0]=name;
const context=E.prepare(state.students,map,{groupSize:4,seatIds:added.seatIds}),result=E.search(context,{seed:3,budgetMs:300,maxEvaluations:1000});
assert.equal(result.valid,true);assert.equal(result.solution[8],fixedName);assert.ok(!result.solution.includes(waiting));
added.seatIds.forEach((id,i)=>{if(id===null)assert.equal(result.solution[i],null);});assert.ok(context.groups.flat().every(i=>added.seatIds[i]!==null),'nonexistent positions cannot belong to a group');
const full=D.reconcile(D.buildProfiles(Array.from({length:50},(_,i)=>({name:'N'+i,class:'01班',subjects:{}})),[],'01班','总分',[],[],{}),null);assert.equal(full.seatMap.length,56);assert.equal(full.seatMap.filter(Boolean).length,50);
const short=D.reconcile(profiles,{students:state.students.slice(0,4),seatMap:state.students.slice(0,4).map(s=>s.name)});assert.equal(short.seatMap.length,16);assert.equal(short.seatMap.filter(Boolean).length,9);
const base=[{id:'A',label:'A',combinedStudentData:[{name:'甲',class:'01班',subjects:{总分:{gradeRank:10},英语:{score:''},英语合:{score:95,gradeRank:10},英语听说:{score:25,gradeRank:20},英语笔试:{score:70,gradeRank:20}}}],allSubjectHeaders:[{name:'总分'},{name:'英语合'},{name:'英语听说'},{name:'英语笔试'}]},
 {id:'B',label:'B',combinedStudentData:[{name:'甲',class:'01班',subjects:{总分:{gradeRank:20},英语:{score:85,gradeRank:20},英语笔试:{score:65,gradeRank:15}}}],allSubjectHeaders:[{name:'总分'},{name:'英语'}]}];
const original=JSON.stringify(base),english=D.buildProfiles(base[0].combinedStudentData,base[0].allSubjectHeaders,'01班','总分',base,[],{currentExam:'A',compareExam:'B',scope:'grade',populations:{A:{'*':100},B:{'*':100}}})[0];
assert.deepEqual(Object.keys(english.subjects),['英语']);assert.equal(english.subjects.英语.percentile,15);assert.equal(english.subjects.英语.sampleCount,2);assert.equal(JSON.stringify(base),original,'alias normalization must not mutate source exams');
const onlyWritten=structuredClone(base);delete onlyWritten[1].combinedStudentData[0].subjects.英语;
const single=D.buildProfiles(base[0].combinedStudentData,base[0].allSubjectHeaders,'01班','总分',onlyWritten,[],{currentExam:'A',compareExam:'B',scope:'grade',populations:{A:{'*':100},B:{'*':100}}})[0];assert.equal(single.subjects.英语.percentile,10);assert.equal(single.subjects.英语.sampleCount,1,'written-only results must not substitute for English totals');
const schoolOnly=[{name:'甲',class:'01班',subjects:{英语合并:{schoolRank:1}}},{name:'乙',class:'01班',subjects:{英语总分:{schoolRank:2}}}];
const schoolProfiles=D.buildProfiles(schoolOnly,[],'01班','总分',[],[],{scope:'class'});assert.deepEqual(Object.keys(schoolProfiles[0].subjects),['英语']);assert.equal(schoolProfiles[0].subjects.英语.percentile,50);
console.log('PASS seating layout: single/full-row additions, stable IDs, absent-cell validation, waiting/fixed preservation, group geometry, search and English aliases without component double-counting');
